synonyms = {
    "bear": "bear",
    "bird": "bird",
    "cat": "cat", "kitty": "cat", "kitten": "cat",
    "chameleon": "chameleon",
    "cheetah": "cheetah",
    "chicken": "chicken", "hen": "chicken",
    "cow": "cow",
    "deer": "deer",
    "dog": "dog", "doge": "dog", "doggy": "dog",
    "duck": "duck", "ducc": "duck",
    "elephant": "elephant",
    "ferret": "ferret",
    "fish": "fish",
    "fox": "fox",
    "frog": "frog",
    "giraffe": "giraffe",
    "guinea pig": "guinea pig",
    "hamster": "hamster",
    "hedgehog": "hedgehog",
    "horse": "horse",
    "kangaroo": "kangaroo", "t-rex deer": "kangaroo",
    "koala": "koala",
    "leopard": "leopard",
    "lion": "lion",
    "meerkat": "meerkat",
    "mouse": "mouse",
    "orangutan": "orangutan",
    "otter": "otter",
    "owl": "owl",
    "panda": "panda",
    "penguin": "penguin",
    "pig": "pig", "hog": "pig",
    "polar bear": "polar bear",
    "rabbit": "rabbit", "bunny": "rabbit", "bun": "rabbit",
    "red panda": "red panda",
    "rhino": "rhino", "rhinoceros": "rhino",
    "sea cucumber": "sea cucumber", "trepang": "sea cucumber",
    "seal": "seal",
    "sheep": "sheep",
    "sloth": "sloth",
    "squirrel": "squirrel",
    "spider": "spider", "spidey": "spider",
    "tiger": "tiger",
    "turtle": "turtle", "tortoise": "turtle"
}

# for animal in (("bear", "bears"),("bird", "birds"),("cat", "cats"),("chameleon", "chameleons"),("cheetah", "cheetahs"),("chicken", "chickens"),("cow", "cows"),("deer", "deer", "deers"),("dog", "dog", "dogs"),("duck", "ducks"),("elephant", "elephants"),("ferret", "ferrets"),("fish", "fish"),("fox", "foxes"),("frog", "frogs"),("giraffe", "giraffes"),("guinea pig", "guinea-pigs"),("hamster", "hamster"),("hedgehog", "hedgehogs"),("horse", "horses"),("kangaroo", "kangaroos"),("koala", "koalas"),("leopard", "leopards"),("lion", "lions"),("meerkat", "meerkats"),("mouse", "mice"),("orangutan", "orangutans"),("otter", "otters"),("owl", "owls"),("panda", "pandas"),("penguin", "penguins"),("pig", "pigs"),("polar bear", "polar-bears"),("rabbit", "rabbits"),("red panda", "red-pandas"),("seal", "seals"),("sheep", "sheep"),("sloth", "slothes"),("squirrel", "squirrels"),("tiger", "tigers"),("turtle", "tortoises")):
#   print("\"" + animal[0] + "\" : \"" + animal[0] + "\",")
